In [ ]:
import pandas as pd

# Crear un diccionario con los datos
data = {
    'Date': pd.date_range(start='2020-01-01', end='2020-02-29'),
    'ExchangeRate': [
        1.2, 1.19, 1.18, 1.21, 1.20, 1.22, 1.21, 1.23, 1.22, 1.20,
        1.19, 1.18, 1.17, 1.16, 1.15, 1.14, 1.13, 1.12, 1.11, 1.10,
        1.09, 1.08, 1.07, 1.06, 1.05, 1.04, 1.03, 1.02, 1.01, 1.00,
        0.99, 0.98, 0.97, 0.96, 0.95, 0.94, 0.93, 0.92, 0.91, 0.90,
        0.89, 0.88, 0.87, 0.86, 0.85, 0.84, 0.83, 0.82, 0.81, 0.80,
        0.79, 0.78, 0.77, 0.76, 0.75, 0.74, 0.73, 0.72, 0.71, 0.70
    ]
}

# Crear un DataFrame
df_exchange_rates = pd.DataFrame(data)

# Guardar el DataFrame en un archivo CSV
df_exchange_rates.to_csv('exchange_rates.csv', index=False)

# Crear un diccionario con los datos
data = {
    'Date': pd.date_range(start='2020-01-01', end='2020-02-29'),
    'ExchangeRate': [
        1.2, 1.19, 1.18, 1.21, 1.20, 1.22, 1.21, 1.23, 1.22, 1.20,
        1.19, 1.18, 1.17, 1.16, 1.15, 1.14, 1.13, 1.12, 1.11, 1.10,
        1.09, 1.08, 1.07, 1.06, 1.05, 1.04, 1.03, 1.02, 1.01, 1.00,
        0.99, 0.98, 0.97, 0.96, 0.95, 0.94, 0.93, 0.92, 0.91, 0.90,
        0.89, 0.88, 0.87, 0.86, 0.85, 0.84, 0.83, 0.82, 0.81, 0.80,
        0.79, 0.78, 0.77, 0.76, 0.75, 0.74, 0.73, 0.72, 0.71, 0.70
    ]
}

# Crear un DataFrame
df_exchange_rates = pd.DataFrame(data)

# Guardar el DataFrame en un archivo CSV
df_exchange_rates.to_csv('exchange_rates.csv', index=False)

In [2]:
# Crear el primer segmento de datos
data1 = {
    'InvoiceNo': ['536365', '536365', '536365', '536365', '536365', '536365', '536365', '536366', '536366', '536367', '536367', '536367', '536367', '536367', '536367', '536367', '536367', '536367', '536367', '536368'],
    'StockCode': ['85123A', '71053', '84406B', '84029G', '84029E', '22752', '21730', '22633', '22632', '84879', '22745', '22748', '22749', '22310', '84969', '22623', '22622', '21754', '21755', '21777'],
    'Description': ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART'],
    'Quantity': [6, 6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6, 6, 3, 2, 3, 3, 4],
    'InvoiceDate': ['12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:28', '12/1/2010 8:28', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:34', '12/1/2010 8:35'],
    'UnitPrice': [2.55, 3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69, 2.1, 2.1, 3.75, 1.65, 4.25, 4.95, 9.95, 5.95, 5.95, 7.95],
    'CustomerID': [17850, 17850, 17850, 17850, 17850, 17850, 17850, 17850, 17850, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df1 = pd.DataFrame(data1)

# Guardar el DataFrame en un archivo CSV
df1.to_csv('retail_data_segment1.csv', index=False)

In [3]:
# Crear el segundo segmento de datos
data2 = {
    'InvoiceNo': ['536368', '536369', '536370', '536370', '536370', '536371', '536371', '536372', '536373', '536374', '536375', '536376', '536377', '536378', '536379', '536380', '536381', '536382', '536383', '536384'],
    'StockCode': ['84988', '21756', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '22112', '22752', '22725', '22624', '22570'],
    'Description': ['SET 2 TEA TOWELS I LOVE LONDON', 'DOORMAT NEW ENGLAND', 'SCANDINAVIAN REDS RIBBONS', 'RED  HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'CHOCOLATE HOT WATER BOTTLE', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS JAR DAISY FRESH COTTON WOOL', 'SET OF 3 CAKE TINS PANTRY DESIGN', 'RED GLASS CANDLE HOLDER STAR'],
    'Quantity': [3, 6, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 6, 2, 6, 6, 6],
    'InvoiceDate': ['12/1/2010 8:35', '12/1/2010 8:45', '12/1/2010 9:00', '12/1/2010 9:00', '12/1/2010 9:00', '12/1/2010 9:01', '12/1/2010 9:01', '12/1/2010 9:02', '12/1/2010 9:03', '12/1/2010 9:04', '12/1/2010 9:05', '12/1/2010 9:06', '12/1/2010 9:07', '12/1/2010 9:08', '12/1/2010 9:09', '12/1/2010 9:10', '12/1/2010 9:11', '12/1/2010 9:12', '12/1/2010 9:13', '12/1/2010 9:14'],
    'UnitPrice': [4.95, 7.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 3.39, 7.65, 4.95, 5.95, 2.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df2 = pd.DataFrame(data2)

# Guardar el DataFrame en un archivo CSV
df2.to_csv('retail_data_segment2.csv', index=False)

In [16]:
# Crear el tercer segmento de datos
data3 = {
    'InvoiceNo': ['536385', '536386', '536387', '536388', '536389', '536390', '536391', '536392', '536393', '536394', '536395', '536396', '536397', '536398', '536399', '536400', '536401', '536402', '536403', '536404'],
    'StockCode': ['22571', '22749', '21756', '22745', '22748', '22752', '22633', '22632', '22111', '21724', '21723', '22623', '22622', '22754', '21754', '21755', '22386', '85099B', '84907B', '84907C'],
    'Description': ['HANGING STAR WITH BELLS', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'DOORMAT NEW ENGLAND', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'SET 7 BABUSHKA NESTING BOXES', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'SCANDINAVIAN REDS RIBBONS', 'RED  HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'COFFEE MUG APPLES DESIGN', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'JUMBO BAG PINK POLKADOT', 'JUMBO BAG RED RETROSPOT', 'PACK OF 12 RED RETROSPOT TISSUES', 'PACK OF 12 BLUE RETROSPOT TISSUES'],
    'Quantity': [6, 8, 6, 6, 6, 2, 6, 6, 10, 10, 20, 3, 2, 6, 3, 3, 10, 10, 20, 20],
    'InvoiceDate': ['12/1/2010 9:15', '12/1/2010 9:16', '12/1/2010 9:17', '12/1/2010 9:18', '12/1/2010 9:19', '12/1/2010 9:20', '12/1/2010 9:21', '12/1/2010 9:22', '12/1/2010 9:23', '12/1/2010 9:24', '12/1/2010 9:25', '12/1/2010 9:26', '12/1/2010 9:27', '12/1/2010 9:28', '12/1/2010 9:29', '12/1/2010 9:30', '12/1/2010 9:31', '12/1/2010 9:32', '12/1/2010 9:33', '12/1/2010 9:34'],
    'UnitPrice': [4.25, 3.75, 7.95, 2.1, 2.1, 7.65, 1.85, 1.85, 1.65, 1.25, 2.95, 4.95, 9.95, 1.95, 5.95, 5.95, 1.95, 1.95, 0.85, 0.85],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df3 = pd.DataFrame(data3)

# Guardar el DataFrame en un archivo CSV
df3.to_csv('retail_data_segment3.csv', index=False)

In [4]:
# Crear el cuarto segmento de datos
data4 = {
    'InvoiceNo': ['536405', '536406', '536407', '536408', '536409', '536410', '536411', '536412', '536413', '536414', '536415', '536416', '536417', '536418', '536419', '536420', '536421', '536422', '536423', '536424'],
    'StockCode': ['84907A', '22751', '22382', '22469', '22384', '22386', '85123A', '71053', '84406B', '84029G', '84029E', '22752', '21730', '22633', '22632', '84879', '22745', '22748', '22749', '22310'],
    'Description': ['PACK OF 12 PINK POLKADOT TISSUES', 'SET OF 7 BABUSHKA NESTING BOXES', 'JUMBO SHOPPER VINTAGE RED PAISLEY', 'HEART OF WICKER LARGE', 'PACK OF 6 SMALL FRUIT STRAWS', 'JUMBO BAG PINK POLKADOT', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY'],
    'Quantity': [20, 10, 5, 6, 15, 10, 6, 6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6],
    'InvoiceDate': ['12/1/2010 9:35', '12/1/2010 9:36', '12/1/2010 9:37', '12/1/2010 9:38', '12/1/2010 9:39', '12/1/2010 9:40', '12/1/2010 9:41', '12/1/2010 9:42', '12/1/2010 9:43', '12/1/2010 9:44', '12/1/2010 9:45', '12/1/2010 9:46', '12/1/2010 9:47', '12/1/2010 9:48', '12/1/2010 9:49', '12/1/2010 9:50', '12/1/2010 9:51', '12/1/2010 9:52', '12/1/2010 9:53', '12/1/2010 9:54'],
    'UnitPrice': [0.85, 7.65, 1.95, 2.95, 1.25, 1.95, 2.55, 3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69, 2.1, 2.1, 3.75, 1.65],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df4 = pd.DataFrame(data4)

# Guardar el DataFrame en un archivo CSV
df4.to_csv('retail_data_segment4.csv', index=False)

In [5]:
# Crear el quinto segmento de datos
data5 = {
    'InvoiceNo': ['536425', '536426', '536427', '536428', '536429', '536430', '536431', '536432', '536433', '536434', '536435', '536436', '536437', '536438', '536439', '536440', '536441', '536442', '536443', '536444'],
    'StockCode': ['84969', '22623', '22622', '21754', '21755', '21777', '84988', '21756', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634'],
    'Description': ['BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART', 'SET 2 TEA TOWELS I LOVE LONDON', 'DOORMAT NEW ENGLAND', 'SCANDINAVIAN REDS RIBBONS', 'RED  HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT'],
    'Quantity': [6, 3, 2, 3, 3, 4, 3, 6, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6],
    'InvoiceDate': ['12/1/2010 9:55', '12/1/2010 9:56', '12/1/2010 9:57', '12/1/2010 9:58', '12/1/2010 9:59', '12/1/2010 10:00', '12/1/2010 10:01', '12/1/2010 10:02', '12/1/2010 10:03', '12/1/2010 10:04', '12/1/2010 10:05', '12/1/2010 10:06', '12/1/2010 10:07', '12/1/2010 10:08', '12/1/2010 10:09', '12/1/2010 10:10', '12/1/2010 10:11', '12/1/2010 10:12', '12/1/2010 10:13', '12/1/2010 10:14'],
    'UnitPrice': [4.25, 4.95, 9.95, 5.95, 5.95, 7.95, 4.95, 7.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df5 = pd.DataFrame(data5)

# Guardar el DataFrame en un archivo CSV
df5.to_csv('retail_data_segment5.csv', index=False)

In [6]:
# Crear el sexto segmento de datos
data6 = {
    'InvoiceNo': ['536445', '536446', '536447', '536448', '536449', '536450', '536451', '536452', '536453', '536454', '536455', '536456', '536457', '536458', '536459', '536460', '536461', '536462', '536463', '536464'],
    'StockCode': ['22960', '21756', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A'],
    'Description': ['JAM MAKING SET WITH JARS', 'DOORMAT NEW ENGLAND', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER'],
    'Quantity': [6, 10, 10, 6, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20, 6],
    'InvoiceDate': ['12/1/2010 10:15', '12/1/2010 10:16', '12/1/2010 10:17', '12/1/2010 10:18', '12/1/2010 10:19', '12/1/2010 10:20', '12/1/2010 10:21', '12/1/2010 10:22', '12/1/2010 10:23', '12/1/2010 10:24', '12/1/2010 10:25', '12/1/2010 10:26', '12/1/2010 10:27', '12/1/2010 10:28', '12/1/2010 10:29', '12/1/2010 10:30', '12/1/2010 10:31', '12/1/2010 10:32', '12/1/2010 10:33', '12/1/2010 10:34'],
    'UnitPrice': [4.25, 7.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df6 = pd.DataFrame(data6)

# Guardar el DataFrame en un archivo CSV
df6.to_csv('retail_data_segment6.csv', index=False)

In [7]:
# Crear el séptimo segmento de datos
data7 = {
    'InvoiceNo': ['536465', '536466', '536467', '536468', '536469', '536470', '536471', '536472', '536473', '536474', '536475', '536476', '536477', '536478', '536479', '536480', '536481', '536482', '536483', '536484'],
    'StockCode': ['71053', '84406B', '84029G', '84029E', '22752', '21730', '22633', '22632', '84879', '22745', '22748', '22749', '22310', '84969', '22623', '22622', '21754', '21755', '21777', '84988'],
    'Description': ['WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART', 'SET 2 TEA TOWELS I LOVE LONDON'],
    'Quantity': [6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6, 6, 3, 2, 3, 3, 4, 3],
    'InvoiceDate': ['12/1/2010 10:35', '12/1/2010 10:36', '12/1/2010 10:37', '12/1/2010 10:38', '12/1/2010 10:39', '12/1/2010 10:40', '12/1/2010 10:41', '12/1/2010 10:42', '12/1/2010 10:43', '12/1/2010 10:44', '12/1/2010 10:45', '12/1/2010 10:46', '12/1/2010 10:47', '12/1/2010 10:48', '12/1/2010 10:49', '12/1/2010 10:50', '12/1/2010 10:51', '12/1/2010 10:52', '12/1/2010 10:53', '12/1/2010 10:54'],
    'UnitPrice': [3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69, 2.1, 2.1, 3.75, 1.65, 4.25, 4.95, 9.95, 5.95, 5.95, 7.95, 4.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df7 = pd.DataFrame(data7)

# Guardar el DataFrame en un archivo CSV
df7.to_csv('retail_data_segment7.csv', index=False)

In [8]:
# Crear el octavo segmento de datos
data8 = {
    'InvoiceNo': ['536485', '536486', '536487', '536488', '536489', '536490', '536491', '536492', '536493', '536494', '536495', '536496', '536497', '536498', '536499', '536500', '536501', '536502', '536503', '536504'],
    'StockCode': ['21756', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914'],
    'Description': ['DOORMAT NEW ENGLAND', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX'],
    'Quantity': [10, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20, 6, 6, 6, 12],
    'InvoiceDate': ['12/1/2010 10:55', '12/1/2010 10:56', '12/1/2010 10:57', '12/1/2010 10:58', '12/1/2010 10:59', '12/1/2010 11:00', '12/1/2010 11:01', '12/1/2010 11:02', '12/1/2010 11:03', '12/1/2010 11:04', '12/1/2010 11:05', '12/1/2010 11:06', '12/1/2010 11:07', '12/1/2010 11:08', '12/1/2010 11:09', '12/1/2010 11:10', '12/1/2010 11:11', '12/1/2010 11:12', '12/1/2010 11:13', '12/1/2010 11:14'],
    'UnitPrice': [7.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df8 = pd.DataFrame(data8)

# Guardar el DataFrame en un archivo CSV
df8.to_csv('retail_data_segment8.csv', index=False)

In [9]:
# Crear el noveno segmento de datos
data9 = {
    'InvoiceNo': ['536505', '536506', '536507', '536508', '536509', '536510', '536511', '536512', '536513', '536514', '536515', '536516', '536517', '536518', '536519', '536520', '536521', '536522', '536523', '536524'],
    'StockCode': ['21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723'],
    'Description': ['RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG'],
    'Quantity': [12, 6, 6, 10, 6, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20],
    'InvoiceDate': ['12/1/2010 11:15', '12/1/2010 11:16', '12/1/2010 11:17', '12/1/2010 11:18', '12/1/2010 11:19', '12/1/2010 11:20', '12/1/2010 11:21', '12/1/2010 11:22', '12/1/2010 11:23', '12/1/2010 11:24', '12/1/2010 11:25', '12/1/2010 11:26', '12/1/2010 11:27', '12/1/2010 11:28', '12/1/2010 11:29', '12/1/2010 11:30', '12/1/2010 11:31', '12/1/2010 11:32', '12/1/2010 11:33', '12/1/2010 11:34'],
    'UnitPrice': [1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df9 = pd.DataFrame(data9)

# Guardar el DataFrame en un archivo CSV
df9.to_csv('retail_data_segment9.csv', index=False)

In [10]:
# Crear el décimo segmento de datos
data10 = {
    'InvoiceNo': ['536525', '536526', '536527', '536528', '536529', '536530', '536531', '536532', '536533', '536534', '536535', '536536', '536537', '536538', '536539', '536540', '536541', '536542', '536543', '536544'],
    'StockCode': ['85123A', '71053', '84406B', '84029G', '84029E', '22752', '21730', '22633', '22632', '84879', '22745', '22748', '22749', '22310', '84969', '22623', '22622', '21754', '21755', '21777'],
    'Description': ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART'],
    'Quantity': [6, 6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6, 6, 3, 2, 3, 3, 4],
    'InvoiceDate': ['12/1/2010 11:35', '12/1/2010 11:36', '12/1/2010 11:37', '12/1/2010 11:38', '12/1/2010 11:39', '12/1/2010 11:40', '12/1/2010 11:41', '12/1/2010 11:42', '12/1/2010 11:43', '12/1/2010 11:44', '12/1/2010 11:45', '12/1/2010 11:46', '12/1/2010 11:47', '12/1/2010 11:48', '12/1/2010 11:49', '12/1/2010 11:50', '12/1/2010 11:51', '12/1/2010 11:52', '12/1/2010 11:53', '12/1/2010 11:54'],
    'UnitPrice': [2.55, 3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69, 2.1, 2.1, 3.75, 1.65, 4.25, 4.95, 9.95, 5.95, 5.95, 7.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df10 = pd.DataFrame(data10)

# Guardar el DataFrame en un archivo CSV
df10.to_csv('retail_data_segment10.csv', index=False)

In [11]:
# Crear el undécimo segmento de datos
data11 = {
    'InvoiceNo': ['536545', '536546', '536547', '536548', '536549', '536550', '536551', '536552', '536553', '536554', '536555', '536556', '536557', '536558', '536559', '536560', '536561', '536562', '536563', '536564'],
    'StockCode': ['22960', '21756', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A'],
    'Description': ['JAM MAKING SET WITH JARS', 'DOORMAT NEW ENGLAND', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER'],
    'Quantity': [6, 10, 10, 6, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20, 6],
    'InvoiceDate': ['12/1/2010 11:55', '12/1/2010 11:56', '12/1/2010 11:57', '12/1/2010 11:58', '12/1/2010 11:59', '12/1/2010 12:00', '12/1/2010 12:01', '12/1/2010 12:02', '12/1/2010 12:03', '12/1/2010 12:04', '12/1/2010 12:05', '12/1/2010 12:06', '12/1/2010 12:07', '12/1/2010 12:08', '12/1/2010 12:09', '12/1/2010 12:10', '12/1/2010 12:11', '12/1/2010 12:12', '12/1/2010 12:13', '12/1/2010 12:14'],
    'UnitPrice': [4.25, 7.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df11 = pd.DataFrame(data11)

# Guardar el DataFrame en un archivo CSV
df11.to_csv('retail_data_segment11.csv', index=False)

In [19]:
# Crear el duodécimo segmento de datos
data12 = {
    'InvoiceNo': ['536565', '536566', '536567', '536568', '536569', '536570', '536571', '536572', '536573', '536574', '536575', '536576', '536577', '536578', '536579', '536580', '536581', '536582', '536583', '536584'],
    'StockCode': ['71053', '84406B', '84029G', '84029E', '22752', '21730', '22633', '22632', '84879', '22745', '22748', '22749', '22310', '84969', '22623', '22622', '21754', '21755', '21777', '84988'],
    'Description': ['WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART', 'SET 2 TEA TOWELS I LOVE LONDON'],
    'Quantity': [6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6, 6, 3, 2, 3, 3, 4, 3],
    'InvoiceDate': ['12/1/2010 12:15', '12/1/2010 12:16', '12/1/2010 12:17', '12/1/2010 12:18', '12/1/2010 12:19', '12/1/2010 12:20', '12/1/2010 12:21', '12/1/2010 12:22', '12/1/2010 12:23', '12/1/2010 12:24', '12/1/2010 12:25', '12/1/2010 12:26', '12/1/2010 12:27', '12/1/2010 12:28', '12/1/2010 12:29', '12/1/2010 12:30', '12/1/2010 12:31', '12/1/2010 12:32', '12/1/2010 12:33', '12/1/2010 12:34'],
    'UnitPrice': [3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69, 2.1, 2.1, 3.75, 1.65, 4.25, 4.95, 9.95, 5.95, 5.95, 7.95, 4.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}
    # Crear un DataFrame
df12 = pd.DataFrame(data12)

# Guardar el DataFrame en un archivo CSV
df12.to_csv('retail_data_segment12.csv', index=False)

In [20]:
# Crear el décimo tercer segmento de datos
data13 = {
    'InvoiceNo': ['536585', '536586', '536587', '536588', '536589', '536590', '536591', '536592', '536593', '536594', '536595', '536596', '536597', '536598', '536599', '536600', '536601', '536602', '536603', '536604'],
    'StockCode': ['21756', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914'],
    'Description': ['DOORMAT NEW ENGLAND', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX'],
    'Quantity': [10, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20, 6, 6, 6, 12],
    'InvoiceDate': ['12/1/2010 12:35', '12/1/2010 12:36', '12/1/2010 12:37', '12/1/2010 12:38', '12/1/2010 12:39', '12/1/2010 12:40', '12/1/2010 12:41', '12/1/2010 12:42', '12/1/2010 12:43', '12/1/2010 12:44', '12/1/2010 12:45', '12/1/2010 12:46', '12/1/2010 12:47', '12/1/2010 12:48', '12/1/2010 12:49', '12/1/2010 12:50', '12/1/2010 12:51', '12/1/2010 12:52', '12/1/2010 12:53', '12/1/2010 12:54'],
    'UnitPrice': [7.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df13 = pd.DataFrame(data13)

# Guardar el DataFrame en un archivo CSV
df13.to_csv('retail_data_segment13.csv', index=False)

In [21]:
# Crear el décimo cuarto segmento de datos
data14 = {
    'InvoiceNo': ['536605', '536606', '536607', '536608', '536609', '536610', '536611', '536612', '536613', '536614', '536615', '536616', '536617', '536618', '536619', '536620', '536621', '536622', '536623', '536624'],
    'StockCode': ['21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723'],
    'Description': ['RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG'],
    'Quantity': [12, 6, 6, 10, 6, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20],
    'InvoiceDate': ['12/1/2010 12:55', '12/1/2010 12:56', '12/1/2010 12:57', '12/1/2010 12:58', '12/1/2010 12:59', '12/1/2010 13:00', '12/1/2010 13:01', '12/1/2010 13:02', '12/1/2010 13:03', '12/1/2010 13:04', '12/1/2010 13:05', '12/1/2010 13:06', '12/1/2010 13:07', '12/1/2010 13:08', '12/1/2010 13:09', '12/1/2010 13:10', '12/1/2010 13:11', '12/1/2010 13:12', '12/1/2010 13:13', '12/1/2010 13:14'],
    'UnitPrice': [1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df14 = pd.DataFrame(data14)

# Guardar el DataFrame en un archivo CSV
df14.to_csv('retail_data_segment14.csv', index=False)

In [22]:
# Crear el décimo quinto segmento de datos
data15 = {
    'InvoiceNo': ['536625', '536626', '536627', '536628', '536629', '536630', '536631', '536632', '536633', '536634', '536635', '536636', '536637', '536638', '536639', '536640', '536641', '536642', '536643', '536644'],
    'StockCode': ['85123A', '71053', '84406B', '84029G', '84029E', '22752', '21730', '22633', '22632', '84879', '22745', '22748', '22749', '22310', '84969', '22623', '22622', '21754', '21755', '21777'],
    'Description': ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART'],
    'Quantity': [6, 6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6, 6, 3, 2, 3, 3, 4],
    'InvoiceDate': ['12/1/2010 13:15', '12/1/2010 13:16', '12/1/2010 13:17', '12/1/2010 13:18', '12/1/2010 13:19', '12/1/2010 13:20', '12/1/2010 13:21', '12/1/2010 13:22', '12/1/2010 13:23', '12/1/2010 13:24', '12/1/2010 13:25', '12/1/2010 13:26', '12/1/2010 13:27', '12/1/2010 13:28', '12/1/2010 13:29', '12/1/2010 13:30', '12/1/2010 13:31', '12/1/2010 13:32', '12/1/2010 13:33', '12/1/2010 13:34'],
    'UnitPrice': [2.55, 3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69, 2.1, 2.1, 3.75, 1.65, 4.25, 4.95, 9.95, 5.95, 5.95, 7.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df15 = pd.DataFrame(data15)

# Guardar el DataFrame en un archivo CSV
df15.to_csv('retail_data_segment15.csv', index=False)

In [23]:
# Crear el décimo sexto segmento de datos
data16 = {
    'InvoiceNo': ['536645', '536646', '536647', '536648', '536649', '536650', '536651', '536652', '536653', '536654', '536655', '536656', '536657', '536658', '536659', '536660', '536661', '536662', '536663', '536664'],
    'StockCode': ['22960', '21756', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A'],
    'Description': ['JAM MAKING SET WITH JARS', 'DOORMAT NEW ENGLAND', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER'],
    'Quantity': [6, 10, 10, 6, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20, 6],
    'InvoiceDate': ['12/1/2010 13:35', '12/1/2010 13:36', '12/1/2010 13:37', '12/1/2010 13:38', '12/1/2010 13:39', '12/1/2010 13:40', '12/1/2010 13:41', '12/1/2010 13:42', '12/1/2010 13:43', '12/1/2010 13:44', '12/1/2010 13:45', '12/1/2010 13:46', '12/1/2010 13:47', '12/1/2010 13:48', '12/1/2010 13:49', '12/1/2010 13:50', '12/1/2010 13:51', '12/1/2010 13:52', '12/1/2010 13:53', '12/1/2010 13:54'],
    'UnitPrice': [4.25, 7.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df16 = pd.DataFrame(data16)

# Guardar el DataFrame en un archivo CSV
df16.to_csv('retail_data_segment16.csv', index=False)

In [24]:
# Crear el décimo séptimo segmento de datos
data17 = {
    'InvoiceNo': ['536665', '536666', '536667', '536668', '536669', '536670', '536671', '536672', '536673', '536674', '536675', '536676', '536677', '536678', '536679', '536680', '536681', '536682', '536683', '536684'],
    'StockCode': ['71053', '84406B', '84029G', '84029E', '22752', '21730', '22633', '22632', '84879', '22745', '22748', '22749', '22310', '84969', '22623', '22622', '21754', '21755', '21777', '84988'],
    'Description': ['WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART', 'SET 2 TEA TOWELS I LOVE LONDON'],
    'Quantity': [6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6, 6, 3, 2, 3, 3, 4, 3],
    'InvoiceDate': ['12/1/2010 13:55', '12/1/2010 13:56', '12/1/2010 13:57', '12/1/2010 13:58', '12/1/2010 13:59', '12/1/2010 14:00', '12/1/2010 14:01', '12/1/2010 14:02', '12/1/2010 14:03', '12/1/2010 14:04', '12/1/2010 14:05', '12/1/2010 14:06', '12/1/2010 14:07', '12/1/2010 14:08', '12/1/2010 14:09', '12/1/2010 14:10', '12/1/2010 14:11', '12/1/2010 14:12', '12/1/2010 14:13', '12/1/2010 14:14'],
    'UnitPrice': [3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69, 2.1, 2.1, 3.75, 1.65, 4.25, 4.95, 9.95, 5.95, 5.95, 7.95, 4.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df17 = pd.DataFrame(data17)

# Guardar el DataFrame en un archivo CSV
df17.to_csv('retail_data_segment17.csv', index=False)

In [25]:
# Crear el décimo octavo segmento de datos
data18 = {
    'InvoiceNo': ['536685', '536686', '536687', '536688', '536689', '536690', '536691', '536692', '536693', '536694', '536695', '536696', '536697', '536698', '536699', '536700', '536701', '536702', '536703', '536704'],
    'StockCode': ['21756', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914'],
    'Description': ['DOORMAT NEW ENGLAND', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX'],
    'Quantity': [10, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20, 6, 6, 6, 12],
    'InvoiceDate': ['12/1/2010 14:15', '12/1/2010 14:16', '12/1/2010 14:17', '12/1/2010 14:18', '12/1/2010 14:19', '12/1/2010 14:20', '12/1/2010 14:21', '12/1/2010 14:22', '12/1/2010 14:23', '12/1/2010 14:24', '12/1/2010 14:25', '12/1/2010 14:26', '12/1/2010 14:27', '12/1/2010 14:28', '12/1/2010 14:29', '12/1/2010 14:30', '12/1/2010 14:31', '12/1/2010 14:32', '12/1/2010 14:33', '12/1/2010 14:34'],
    'UnitPrice': [7.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df18 = pd.DataFrame(data18)

# Guardar el DataFrame en un archivo CSV
df18.to_csv('retail_data_segment18.csv', index=False)

In [26]:
# Crear el décimo noveno segmento de datos
data19 = {
    'InvoiceNo': ['536705', '536706', '536707', '536708', '536709', '536710', '536711', '536712', '536713', '536714', '536715', '536716', '536717', '536718', '536719', '536720', '536721', '536722', '536723', '536724'],
    'StockCode': ['21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723', '85123A', '71053', '22632', '21914', '21731', '22960', '22139', '22112', '22634', '22111', '21724', '21723'],
    'Description': ['RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT', 'BLUE HARMONICA IN BOX', 'RED TOADSTOOL LED NIGHT LIGHT', 'JAM MAKING SET WITH JARS', 'RETROSPOT TEA SET CERAMIC 11 PC', 'CHOCOLATE HOT WATER BOTTLE', 'BAKING SET 9 PIECE RETROSPOT', 'SCANDINAVIAN REDS RIBBONS', 'RED HARMONICA IN BOX', 'STRIPED CHARLIE+LOLA CHARLOTTE BAG'],
    'Quantity': [12, 6, 6, 10, 6, 10, 10, 20, 6, 6, 6, 12, 12, 6, 6, 10, 6, 10, 10, 20],
    'InvoiceDate': ['12/1/2010 14:35', '12/1/2010 14:36', '12/1/2010 14:37', '12/1/2010 14:38', '12/1/2010 14:39', '12/1/2010 14:40', '12/1/2010 14:41', '12/1/2010 14:42', '12/1/2010 14:43', '12/1/2010 14:44', '12/1/2010 14:45', '12/1/2010 14:46', '12/1/2010 14:47', '12/1/2010 14:48', '12/1/2010 14:49', '12/1/2010 14:50', '12/1/2010 14:51', '12/1/2010 14:52', '12/1/2010 14:53', '12/1/2010 14:54'],
    'UnitPrice': [1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95, 2.55, 3.39, 1.85, 1.25, 1.65, 4.25, 6.95, 3.39, 4.95, 1.65, 1.25, 2.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df19 = pd.DataFrame(data19)

# Guardar el DataFrame en un archivo CSV
df19.to_csv('retail_data_segment19.csv', index=False)

In [27]:
# Crear el vigésimo segmento de datos
data20 = {
    'InvoiceNo': ['536725', '536726', '536727', '536728', '536729', '536730', '536731', '536732', '536733', '536734', '536735', '536736', '536737', '536738', '536739', '536740', '536741', '536742', '536743', '536744'],
    'StockCode': ['85123A', '71053', '84406B', '84029G', '84029E', '22752', '21730', '22633', '22632', '84879', '22745', '22748', '22749', '22310', '84969', '22623', '22622', '21754', '21755', '21777'],
    'Description': ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT', 'POPPY\'S PLAYHOUSE BEDROOM', 'POPPY\'S PLAYHOUSE KITCHEN', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART'],
    'Quantity': [6, 6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6, 6, 3, 2, 3, 3, 4],
    'InvoiceDate': ['12/1/2010 14:55', '12/1/2010 14:56', '12/1/2010 14:57', '12/1/2010 14:58', '12/1/2010 14:59', '12/1/2010 15:00', '12/1/2010 15:01', '12/1/2010 15:02', '12/1/2010 15:03', '12/1/2010 15:04', '12/1/2010 15:05', '12/1/2010 15:06', '12/1/2010 15:07', '12/1/2010 15:08', '12/1/2010 15:09', '12/1/2010 15:10', '12/1/2010 15:11', '12/1/2010 15:12', '12/1/2010 15:13', '12/1/2010 15:14'],
    'UnitPrice': [2.55, 3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69, 2.1, 2.1, 3.75, 1.65, 4.25, 4.95, 9.95, 5.95, 5.95, 7.95],
    'CustomerID': [13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047, 13047],
    'Country': ['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']
}

# Crear un DataFrame
df20 = pd.DataFrame(data20)

# Guardar el DataFrame en un archivo CSV
df20.to_csv('retail_data_segment20.csv', index=False)

In [28]:
# Leer todos los segmentos de archivos CSV
df1 = pd.read_csv('retail_data_segment1.csv')
df2 = pd.read_csv('retail_data_segment2.csv')
df3 = pd.read_csv('retail_data_segment3.csv')
df4 = pd.read_csv('retail_data_segment4.csv')
df5 = pd.read_csv('retail_data_segment5.csv')
df6 = pd.read_csv('retail_data_segment6.csv')
df7 = pd.read_csv('retail_data_segment7.csv')
df8 = pd.read_csv('retail_data_segment8.csv')
df9 = pd.read_csv('retail_data_segment9.csv')
df10 = pd.read_csv('retail_data_segment10.csv')
df11 = pd.read_csv('retail_data_segment11.csv')
df12 = pd.read_csv('retail_data_segment12.csv')
df13 = pd.read_csv('retail_data_segment13.csv')
df14 = pd.read_csv('retail_data_segment14.csv')
df15 = pd.read_csv('retail_data_segment15.csv')
df16 = pd.read_csv('retail_data_segment16.csv')
df17 = pd.read_csv('retail_data_segment17.csv')
df18 = pd.read_csv('retail_data_segment18.csv')
df19 = pd.read_csv('retail_data_segment19.csv')
df20 = pd.read_csv('retail_data_segment20.csv')

# Combinar los DataFrames
df_combined = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20])

# Guardar el DataFrame combinado en un archivo CSV
df_combined.to_csv('retail_data_complete.csv', index=False)